column_width = 100                   # NOTE: conform with Linux max line length
indent_width = 4
line_endings = "Unix"
quote_style = "AutoPreferDouble"
call_parentheses = "None"
collapse_simple_statement = "Always"
